remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Anything can be numbers, numbers can be anything... What data looks like, in color and in 3D.
description: "Browse data using Conti's 2D projector as well as 3D variants."
show_downloads: false
