remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: (void *) · voidstarhq.github.io
description: anything can be numbers, numbers can be anything... What does data look like, in color and in 3D.
show_downloads: false
